name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests with Maven
        run: mvn clean test

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl
          curl -sSL https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip -o allure.zip
          unzip allure.zip -d $HOME/allure
          export PATH=$HOME/allure/allure-2.30.0/bin:$PATH
          allure --version

      - name: Generate Allure Report
        run: |
          if [ -d "target/allure-results" ]; then
            mvn allure:report
          else
            echo "No test results found, skipping Allure report generation."
          fi

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages
